/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */

import { faker } from "@faker-js/faker";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import axios from "axios";
import type { RequestHandlerOptions } from "msw";

import { delay, HttpResponse, http } from "msw";
import type {
	ClothingItem,
	ClothingItemInput,
	GetAllClothes200,
	GetAllClothesParams,
	GetAllHabits200,
	GetAllHabitsParams,
	GetHabitLogs200,
	GetHabitLogsParams,
	GetHabitStatisticsParams,
	Habit,
	HabitInput,
	HabitLog,
	HabitStatistics,
	LoginUser200,
	LoginUserBody,
	RefreshToken200,
	RegisterUserBody,
	TrackHabitBody,
	UpdateCurrentUserBody,
	UserResponse,
} from "./schemas";

/**
 * @summary Register new user
 */
export const registerUser = <TData = AxiosResponse<UserResponse>>(
	registerUserBody: RegisterUserBody,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/auth/register`, registerUserBody, options);
};

/**
 * @summary Login user
 */
export const loginUser = <TData = AxiosResponse<LoginUser200>>(
	loginUserBody: LoginUserBody,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/auth/login`, loginUserBody, options);
};

/**
 * @summary Logout user
 */
export const logoutUser = <TData = AxiosResponse<void>>(
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/auth/logout`, undefined, options);
};

/**
 * @summary Refresh access token
 */
export const refreshToken = <TData = AxiosResponse<RefreshToken200>>(
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/auth/refresh`, undefined, options);
};

/**
 * @summary Get current user profile
 */
export const getCurrentUser = <TData = AxiosResponse<UserResponse>>(
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/users/me`, options);
};

/**
 * @summary Update current user profile
 */
export const updateCurrentUser = <TData = AxiosResponse<UserResponse>>(
	updateCurrentUserBody: UpdateCurrentUserBody,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.put(`/users/me`, updateCurrentUserBody, options);
};

/**
 * @summary Get all clothes for current user
 */
export const getAllClothes = <TData = AxiosResponse<GetAllClothes200>>(
	params?: GetAllClothesParams,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/clothes`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

/**
 * @summary Add new clothing item
 */
export const createClothingItem = <TData = AxiosResponse<ClothingItem>>(
	clothingItemInput: ClothingItemInput,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/clothes`, clothingItemInput, options);
};

/**
 * @summary Get clothing item by ID
 */
export const getClothingItemById = <TData = AxiosResponse<ClothingItem>>(
	id: string,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/clothes/${id}`, options);
};

/**
 * @summary Update clothing item
 */
export const updateClothingItem = <TData = AxiosResponse<ClothingItem>>(
	id: string,
	clothingItemInput: ClothingItemInput,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.put(`/clothes/${id}`, clothingItemInput, options);
};

/**
 * @summary Delete clothing item
 */
export const deleteClothingItem = <TData = AxiosResponse<void>>(
	id: string,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.delete(`/clothes/${id}`, options);
};

/**
 * @summary Get all habits for current user
 */
export const getAllHabits = <TData = AxiosResponse<GetAllHabits200>>(
	params?: GetAllHabitsParams,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/habits`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

/**
 * @summary Create new habit
 */
export const createHabit = <TData = AxiosResponse<Habit>>(
	habitInput: HabitInput,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/habits`, habitInput, options);
};

/**
 * @summary Get habit by ID
 */
export const getHabitById = <TData = AxiosResponse<Habit>>(
	id: string,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/habits/${id}`, options);
};

/**
 * @summary Update habit
 */
export const updateHabit = <TData = AxiosResponse<Habit>>(
	id: string,
	habitInput: HabitInput,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.put(`/habits/${id}`, habitInput, options);
};

/**
 * @summary Delete habit
 */
export const deleteHabit = <TData = AxiosResponse<void>>(
	id: string,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.delete(`/habits/${id}`, options);
};

/**
 * @summary Track habit completion
 */
export const trackHabit = <TData = AxiosResponse<HabitLog>>(
	id: string,
	trackHabitBody: TrackHabitBody,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.post(`/habits/${id}/track`, trackHabitBody, options);
};

/**
 * @summary Get habit completion logs
 */
export const getHabitLogs = <TData = AxiosResponse<GetHabitLogs200>>(
	id: string,
	params?: GetHabitLogsParams,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/habits/${id}/logs`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

/**
 * @summary Get habit statistics
 */
export const getHabitStatistics = <TData = AxiosResponse<HabitStatistics>>(
	id: string,
	params?: GetHabitStatisticsParams,
	options?: AxiosRequestConfig,
): Promise<TData> => {
	return axios.get(`/habits/${id}/statistics`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export type RegisterUserResult = AxiosResponse<UserResponse>;
export type LoginUserResult = AxiosResponse<LoginUser200>;
export type LogoutUserResult = AxiosResponse<void>;
export type RefreshTokenResult = AxiosResponse<RefreshToken200>;
export type GetCurrentUserResult = AxiosResponse<UserResponse>;
export type UpdateCurrentUserResult = AxiosResponse<UserResponse>;
export type GetAllClothesResult = AxiosResponse<GetAllClothes200>;
export type CreateClothingItemResult = AxiosResponse<ClothingItem>;
export type GetClothingItemByIdResult = AxiosResponse<ClothingItem>;
export type UpdateClothingItemResult = AxiosResponse<ClothingItem>;
export type DeleteClothingItemResult = AxiosResponse<void>;
export type GetAllHabitsResult = AxiosResponse<GetAllHabits200>;
export type CreateHabitResult = AxiosResponse<Habit>;
export type GetHabitByIdResult = AxiosResponse<Habit>;
export type UpdateHabitResult = AxiosResponse<Habit>;
export type DeleteHabitResult = AxiosResponse<void>;
export type TrackHabitResult = AxiosResponse<HabitLog>;
export type GetHabitLogsResult = AxiosResponse<GetHabitLogs200>;
export type GetHabitStatisticsResult = AxiosResponse<HabitStatistics>;

export const getRegisterUserResponseMock = (
	overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
	id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
	email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	created_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	updated_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	...overrideResponse,
});

export const getLoginUserResponseMock = (
	overrideResponse: Partial<LoginUser200> = {},
): LoginUser200 => ({
	token: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	user: faker.helpers.arrayElement([
		{
			id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
			email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
			name: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			updated_at: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getRefreshTokenResponseMock = (
	overrideResponse: Partial<RefreshToken200> = {},
): RefreshToken200 => ({
	token: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	...overrideResponse,
});

export const getGetCurrentUserResponseMock = (
	overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
	id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
	email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	created_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	updated_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	...overrideResponse,
});

export const getUpdateCurrentUserResponseMock = (
	overrideResponse: Partial<UserResponse> = {},
): UserResponse => ({
	id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
	email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	created_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	updated_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	...overrideResponse,
});

export const getGetAllClothesResponseMock = (
	overrideResponse: Partial<GetAllClothes200> = {},
): GetAllClothes200 => ({
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			...{
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				category: faker.helpers.arrayElement([
					"tops",
					"bottoms",
					"outerwear",
					"shoes",
					"accessories",
				] as const),
				brand: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				color: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				season: faker.helpers.arrayElement([
					faker.helpers.arrayElement([
						"spring",
						"summer",
						"autumn",
						"winter",
						"all_season",
					] as const),
					undefined,
				]),
				purchase_date: faker.helpers.arrayElement([
					faker.date.past().toISOString().split("T")[0],
					undefined,
				]),
				purchase_price: faker.helpers.arrayElement([
					faker.number.float({
						min: undefined,
						max: undefined,
						fractionDigits: 2,
					}),
					undefined,
				]),
				image_url: faker.helpers.arrayElement([
					faker.internet.url(),
					undefined,
				]),
				notes: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
			},
			...{
				id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
				user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
				wear_count: faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					undefined,
				]),
				last_worn_at: faker.helpers.arrayElement([
					`${faker.date.past().toISOString().split(".")[0]}Z`,
					undefined,
				]),
				created_at: faker.helpers.arrayElement([
					`${faker.date.past().toISOString().split(".")[0]}Z`,
					undefined,
				]),
				updated_at: faker.helpers.arrayElement([
					`${faker.date.past().toISOString().split(".")[0]}Z`,
					undefined,
				]),
			},
		})),
		undefined,
	]),
	pagination: faker.helpers.arrayElement([
		{
			page: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			limit: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			total: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			total_pages: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getCreateClothingItemResponseMock = (): ClothingItem => ({
	...{
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		category: faker.helpers.arrayElement([
			"tops",
			"bottoms",
			"outerwear",
			"shoes",
			"accessories",
		] as const),
		brand: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		color: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		season: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				"spring",
				"summer",
				"autumn",
				"winter",
				"all_season",
			] as const),
			undefined,
		]),
		purchase_date: faker.helpers.arrayElement([
			faker.date.past().toISOString().split("T")[0],
			undefined,
		]),
		purchase_price: faker.helpers.arrayElement([
			faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
			undefined,
		]),
		image_url: faker.helpers.arrayElement([faker.internet.url(), undefined]),
		notes: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	},
	...{
		id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		wear_count: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		last_worn_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		updated_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
	},
});

export const getGetClothingItemByIdResponseMock = (): ClothingItem => ({
	...{
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		category: faker.helpers.arrayElement([
			"tops",
			"bottoms",
			"outerwear",
			"shoes",
			"accessories",
		] as const),
		brand: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		color: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		season: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				"spring",
				"summer",
				"autumn",
				"winter",
				"all_season",
			] as const),
			undefined,
		]),
		purchase_date: faker.helpers.arrayElement([
			faker.date.past().toISOString().split("T")[0],
			undefined,
		]),
		purchase_price: faker.helpers.arrayElement([
			faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
			undefined,
		]),
		image_url: faker.helpers.arrayElement([faker.internet.url(), undefined]),
		notes: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	},
	...{
		id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		wear_count: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		last_worn_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		updated_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
	},
});

export const getUpdateClothingItemResponseMock = (): ClothingItem => ({
	...{
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		category: faker.helpers.arrayElement([
			"tops",
			"bottoms",
			"outerwear",
			"shoes",
			"accessories",
		] as const),
		brand: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		color: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		season: faker.helpers.arrayElement([
			faker.helpers.arrayElement([
				"spring",
				"summer",
				"autumn",
				"winter",
				"all_season",
			] as const),
			undefined,
		]),
		purchase_date: faker.helpers.arrayElement([
			faker.date.past().toISOString().split("T")[0],
			undefined,
		]),
		purchase_price: faker.helpers.arrayElement([
			faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
			undefined,
		]),
		image_url: faker.helpers.arrayElement([faker.internet.url(), undefined]),
		notes: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	},
	...{
		id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		wear_count: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		last_worn_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		updated_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
	},
});

export const getGetAllHabitsResponseMock = (
	overrideResponse: Partial<GetAllHabits200> = {},
): GetAllHabits200 => ({
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			...{
				name: faker.string.alpha({ length: { min: 10, max: 20 } }),
				description: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				frequency: faker.helpers.arrayElement([
					"daily",
					"weekly",
					"monthly",
				] as const),
				target_count: faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					undefined,
				]),
				reminder_time: faker.helpers.arrayElement([
					faker.helpers.fromRegExp("^([01]d|2[0-3]):([0-5]d)$"),
					undefined,
				]),
				icon: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
				color: faker.helpers.arrayElement([
					faker.string.alpha({ length: { min: 10, max: 20 } }),
					undefined,
				]),
			},
			...{
				id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
				user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
				status: faker.helpers.arrayElement([
					faker.helpers.arrayElement(["active", "archived"] as const),
					undefined,
				]),
				current_streak: faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					undefined,
				]),
				longest_streak: faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					undefined,
				]),
				total_completions: faker.helpers.arrayElement([
					faker.number.int({ min: undefined, max: undefined }),
					undefined,
				]),
				created_at: faker.helpers.arrayElement([
					`${faker.date.past().toISOString().split(".")[0]}Z`,
					undefined,
				]),
				updated_at: faker.helpers.arrayElement([
					`${faker.date.past().toISOString().split(".")[0]}Z`,
					undefined,
				]),
			},
		})),
		undefined,
	]),
	pagination: faker.helpers.arrayElement([
		{
			page: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			limit: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			total: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			total_pages: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getCreateHabitResponseMock = (): Habit => ({
	...{
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		frequency: faker.helpers.arrayElement([
			"daily",
			"weekly",
			"monthly",
		] as const),
		target_count: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		reminder_time: faker.helpers.arrayElement([
			faker.helpers.fromRegExp("^([01]d|2[0-3]):([0-5]d)$"),
			undefined,
		]),
		icon: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		color: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	},
	...{
		id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		status: faker.helpers.arrayElement([
			faker.helpers.arrayElement(["active", "archived"] as const),
			undefined,
		]),
		current_streak: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		longest_streak: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		total_completions: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		updated_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
	},
});

export const getGetHabitByIdResponseMock = (): Habit => ({
	...{
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		frequency: faker.helpers.arrayElement([
			"daily",
			"weekly",
			"monthly",
		] as const),
		target_count: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		reminder_time: faker.helpers.arrayElement([
			faker.helpers.fromRegExp("^([01]d|2[0-3]):([0-5]d)$"),
			undefined,
		]),
		icon: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		color: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	},
	...{
		id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		status: faker.helpers.arrayElement([
			faker.helpers.arrayElement(["active", "archived"] as const),
			undefined,
		]),
		current_streak: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		longest_streak: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		total_completions: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		updated_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
	},
});

export const getUpdateHabitResponseMock = (): Habit => ({
	...{
		name: faker.string.alpha({ length: { min: 10, max: 20 } }),
		description: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		frequency: faker.helpers.arrayElement([
			"daily",
			"weekly",
			"monthly",
		] as const),
		target_count: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		reminder_time: faker.helpers.arrayElement([
			faker.helpers.fromRegExp("^([01]d|2[0-3]):([0-5]d)$"),
			undefined,
		]),
		icon: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		color: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	},
	...{
		id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		user_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
		status: faker.helpers.arrayElement([
			faker.helpers.arrayElement(["active", "archived"] as const),
			undefined,
		]),
		current_streak: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		longest_streak: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		total_completions: faker.helpers.arrayElement([
			faker.number.int({ min: undefined, max: undefined }),
			undefined,
		]),
		created_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
		updated_at: faker.helpers.arrayElement([
			`${faker.date.past().toISOString().split(".")[0]}Z`,
			undefined,
		]),
	},
});

export const getTrackHabitResponseMock = (
	overrideResponse: Partial<HabitLog> = {},
): HabitLog => ({
	id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
	habit_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
	completed_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	note: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	created_at: faker.helpers.arrayElement([
		`${faker.date.past().toISOString().split(".")[0]}Z`,
		undefined,
	]),
	...overrideResponse,
});

export const getGetHabitLogsResponseMock = (
	overrideResponse: Partial<GetHabitLogs200> = {},
): GetHabitLogs200 => ({
	data: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => ({
			id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
			habit_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
			completed_at: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
			note: faker.helpers.arrayElement([
				faker.string.alpha({ length: { min: 10, max: 20 } }),
				undefined,
			]),
			created_at: faker.helpers.arrayElement([
				`${faker.date.past().toISOString().split(".")[0]}Z`,
				undefined,
			]),
		})),
		undefined,
	]),
	pagination: faker.helpers.arrayElement([
		{
			page: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			limit: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			total: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
			total_pages: faker.helpers.arrayElement([
				faker.number.int({ min: undefined, max: undefined }),
				undefined,
			]),
		},
		undefined,
	]),
	...overrideResponse,
});

export const getGetHabitStatisticsResponseMock = (
	overrideResponse: Partial<HabitStatistics> = {},
): HabitStatistics => ({
	habit_id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
	period: faker.helpers.arrayElement([
		faker.helpers.arrayElement(["week", "month", "year"] as const),
		undefined,
	]),
	completion_rate: faker.helpers.arrayElement([
		faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
		undefined,
	]),
	total_completions: faker.helpers.arrayElement([
		faker.number.int({ min: undefined, max: undefined }),
		undefined,
	]),
	current_streak: faker.helpers.arrayElement([
		faker.number.int({ min: undefined, max: undefined }),
		undefined,
	]),
	longest_streak: faker.helpers.arrayElement([
		faker.number.int({ min: undefined, max: undefined }),
		undefined,
	]),
	average_per_period: faker.helpers.arrayElement([
		faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
		undefined,
	]),
	...overrideResponse,
});

export const getRegisterUserMockHandler = (
	overrideResponse?:
		| UserResponse
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<UserResponse> | UserResponse),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/auth/register",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getRegisterUserResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getLoginUserMockHandler = (
	overrideResponse?:
		| LoginUser200
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<LoginUser200> | LoginUser200),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/auth/login",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getLoginUserResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getLogoutUserMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/auth/logout",
		async (info) => {
			await delay(1000);
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}
			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getRefreshTokenMockHandler = (
	overrideResponse?:
		| RefreshToken200
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<RefreshToken200> | RefreshToken200),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/auth/refresh",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getRefreshTokenResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetCurrentUserMockHandler = (
	overrideResponse?:
		| UserResponse
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<UserResponse> | UserResponse),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/users/me",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetCurrentUserResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdateCurrentUserMockHandler = (
	overrideResponse?:
		| UserResponse
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<UserResponse> | UserResponse),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/users/me",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdateCurrentUserResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetAllClothesMockHandler = (
	overrideResponse?:
		| GetAllClothes200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetAllClothes200> | GetAllClothes200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/clothes",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetAllClothesResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getCreateClothingItemMockHandler = (
	overrideResponse?:
		| ClothingItem
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<ClothingItem> | ClothingItem),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/clothes",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getCreateClothingItemResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetClothingItemByIdMockHandler = (
	overrideResponse?:
		| ClothingItem
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<ClothingItem> | ClothingItem),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/clothes/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetClothingItemByIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdateClothingItemMockHandler = (
	overrideResponse?:
		| ClothingItem
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<ClothingItem> | ClothingItem),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/clothes/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdateClothingItemResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeleteClothingItemMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/clothes/:id",
		async (info) => {
			await delay(1000);
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}
			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getGetAllHabitsMockHandler = (
	overrideResponse?:
		| GetAllHabits200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetAllHabits200> | GetAllHabits200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/habits",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetAllHabitsResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getCreateHabitMockHandler = (
	overrideResponse?:
		| Habit
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<Habit> | Habit),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/habits",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getCreateHabitResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetHabitByIdMockHandler = (
	overrideResponse?:
		| Habit
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Habit> | Habit),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/habits/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetHabitByIdResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getUpdateHabitMockHandler = (
	overrideResponse?:
		| Habit
		| ((
				info: Parameters<Parameters<typeof http.put>[1]>[0],
		  ) => Promise<Habit> | Habit),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/habits/:id",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getUpdateHabitResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getDeleteHabitMockHandler = (
	overrideResponse?:
		| void
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		"*/habits/:id",
		async (info) => {
			await delay(1000);
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}
			return new HttpResponse(null, { status: 204 });
		},
		options,
	);
};

export const getTrackHabitMockHandler = (
	overrideResponse?:
		| HabitLog
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<HabitLog> | HabitLog),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/habits/:id/track",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getTrackHabitResponseMock(),
				),
				{ status: 201, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetHabitLogsMockHandler = (
	overrideResponse?:
		| GetHabitLogs200
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<GetHabitLogs200> | GetHabitLogs200),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/habits/:id/logs",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetHabitLogsResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};

export const getGetHabitStatisticsMockHandler = (
	overrideResponse?:
		| HabitStatistics
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<HabitStatistics> | HabitStatistics),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/habits/:id/statistics",
		async (info) => {
			await delay(1000);

			return new HttpResponse(
				JSON.stringify(
					overrideResponse !== undefined
						? typeof overrideResponse === "function"
							? await overrideResponse(info)
							: overrideResponse
						: getGetHabitStatisticsResponseMock(),
				),
				{ status: 200, headers: { "Content-Type": "application/json" } },
			);
		},
		options,
	);
};
export const getUtakataServerMock = () => [
	getRegisterUserMockHandler(),
	getLoginUserMockHandler(),
	getLogoutUserMockHandler(),
	getRefreshTokenMockHandler(),
	getGetCurrentUserMockHandler(),
	getUpdateCurrentUserMockHandler(),
	getGetAllClothesMockHandler(),
	getCreateClothingItemMockHandler(),
	getGetClothingItemByIdMockHandler(),
	getUpdateClothingItemMockHandler(),
	getDeleteClothingItemMockHandler(),
	getGetAllHabitsMockHandler(),
	getCreateHabitMockHandler(),
	getGetHabitByIdMockHandler(),
	getUpdateHabitMockHandler(),
	getDeleteHabitMockHandler(),
	getTrackHabitMockHandler(),
	getGetHabitLogsMockHandler(),
	getGetHabitStatisticsMockHandler(),
];
