/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */

export type ClothingItemAllOf = {
	id?: string;
	user_id?: string;
	wear_count?: number;
	last_worn_at?: string;
	created_at?: string;
	updated_at?: string;
};
