/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */
import type { ClothingItemInputCategory } from "./clothingItemInputCategory";
import type { ClothingItemInputSeason } from "./clothingItemInputSeason";

export interface ClothingItemInput {
	name: string;
	category: ClothingItemInputCategory;
	brand?: string;
	color?: string;
	season?: ClothingItemInputSeason;
	purchase_date?: string;
	purchase_price?: number;
	image_url?: string;
	notes?: string;
}
