/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */

export type ClothingItemInputSeason =
	(typeof ClothingItemInputSeason)[keyof typeof ClothingItemInputSeason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClothingItemInputSeason = {
	spring: "spring",
	summer: "summer",
	autumn: "autumn",
	winter: "winter",
	all_season: "all_season",
} as const;
