/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */

export type ClothingItemInputCategory =
	(typeof ClothingItemInputCategory)[keyof typeof ClothingItemInputCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClothingItemInputCategory = {
	tops: "tops",
	bottoms: "bottoms",
	outerwear: "outerwear",
	shoes: "shoes",
	accessories: "accessories",
} as const;
