/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */
import type { ClothingItem } from "./clothingItem";
import type { Pagination } from "./pagination";

export type GetAllClothes200 = {
	data?: ClothingItem[];
	pagination?: Pagination;
};
