/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */
import type { GetAllClothesCategory } from "./getAllClothesCategory";
import type { GetAllClothesSeason } from "./getAllClothesSeason";

export type GetAllClothesParams = {
	category?: GetAllClothesCategory;
	season?: GetAllClothesSeason;
	page?: number;
	limit?: number;
};
