/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */

export type GetAllClothesSeason =
	(typeof GetAllClothesSeason)[keyof typeof GetAllClothesSeason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllClothesSeason = {
	spring: "spring",
	summer: "summer",
	autumn: "autumn",
	winter: "winter",
	all_season: "all_season",
} as const;
