/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */
import type { HabitStatisticsPeriod } from "./habitStatisticsPeriod";

export interface HabitStatistics {
	habit_id?: string;
	period?: HabitStatisticsPeriod;
	/** Percentage of target completions achieved */
	completion_rate?: number;
	total_completions?: number;
	current_streak?: number;
	longest_streak?: number;
	average_per_period?: number;
}
