/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */
import type { HabitInputFrequency } from "./habitInputFrequency";

export interface HabitInput {
	name: string;
	description?: string;
	frequency: HabitInputFrequency;
	/** Target number of completions per frequency period */
	target_count?: number;
	/** @pattern ^([01]\d|2[0-3]):([0-5]\d)$ */
	reminder_time?: string;
	icon?: string;
	color?: string;
}
