/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Utakata Server
 * Utakata Kyosui Monorepo Service API.
Used Backend Framework is Loco.rs
Axum based Backend Framework for Rust.

Life Management Service.
Create Life Log

 * OpenAPI spec version: 0.1.0
 */
import type { HabitAllOfStatus } from "./habitAllOfStatus";

export type HabitAllOf = {
	id?: string;
	user_id?: string;
	status?: HabitAllOfStatus;
	current_streak?: number;
	longest_streak?: number;
	total_completions?: number;
	created_at?: string;
	updated_at?: string;
};
