use crate::analyzer::{ResourceInfo, FieldInfo, FieldType, RelationshipInfo, RelationshipType};
use convert_case::{Case, Casing};

pub struct LocoScaffoldGenerator;

impl LocoScaffoldGenerator {
    pub fn new() -> Self {
        Self
    }

    /// リソース情報からLocoスキャフォールドコマンドを生成
    pub fn generate_commands(&self, resources: &[ResourceInfo], api_only: bool) -> Vec<String> {
        resources
            .iter()
            .map(|resource| self.generate_single_command(resource, api_only))
            .collect()
    }

    /// 単一リソースのスキャフォールドコマンド生成
    fn generate_single_command(&self, resource: &ResourceInfo, api_only: bool) -> String {
        let resource_name = &resource.name;
        let fields_str = self.format_fields(&resource.fields);
        let api_flag = if api_only { " --api" } else { "" };
        
        format!("cargo loco generate scaffold {} {}{}", 
            resource_name, fields_str, api_flag)
    }

    /// フィールド情報をLoco形式の文字列に変換
    fn format_fields(&self, fields: &[FieldInfo]) -> String {
        if fields.is_empty() {
            return String::new();
        }
        
        fields
            .iter()
            .map(|field| self.format_single_field(field))
            .collect::<Vec<_>>()
            .join(" ")
    }

    /// 単一フィールドをLoco形式に変換
    fn format_single_field(&self, field: &FieldInfo) -> String {
        let field_name = &field.name;
        let type_str = self.format_field_type(&field.field_type);
        
        // 制約を优先度順で処理: unique(^) > required(!)
        let constraint_suffix = if field.unique {
            "^"
        } else if field.required {
            "!"
        } else {
            ""
        };
        
        match &field.field_type {
            FieldType::References(table_name) => {
                format!("{}:references:{}{}", field_name, table_name, constraint_suffix)
            }
            _ => {
                format!("{}:{}{}", field_name, type_str, constraint_suffix)
            }
        }
    }

    /// FieldTypeをLocoの型文字列に変換
    fn format_field_type(&self, field_type: &FieldType) -> String {
        match field_type {
            // String types
            FieldType::String => "string".to_string(),
            FieldType::Text => "text".to_string(),
            FieldType::Uuid => "uuid".to_string(),
            
            // Numeric types
            FieldType::Integer => "int".to_string(),
            FieldType::BigInt => "big_int".to_string(),
            FieldType::SmallInt => "small_int".to_string(),
            FieldType::Unsigned => "unsigned".to_string(),
            FieldType::BigUnsigned => "big_unsigned".to_string(),
            FieldType::SmallUnsigned => "small_unsigned".to_string(),
            FieldType::Float => "float".to_string(),
            FieldType::Double => "double".to_string(),
            FieldType::Decimal => "decimal".to_string(),
            FieldType::DecimalLen => "decimal_len".to_string(),
            FieldType::Money => "money".to_string(),
            
            // Other types
            FieldType::Boolean => "bool".to_string(),
            FieldType::Date => "date".to_string(),
            FieldType::DateTime => "date_time".to_string(),
            FieldType::TimestampWithTimeZone => "tstz".to_string(),
            FieldType::Json => "json".to_string(),
            FieldType::JsonBinary => "jsonb".to_string(),
            FieldType::Blob => "blob".to_string(),
            FieldType::BinaryLen => "binary_len".to_string(),
            FieldType::VarBinary => "var_binary".to_string(),
            FieldType::Array => "array".to_string(),
            
            // References
            FieldType::References(_) => "references".to_string(),
        }
    }

    /// バッチスクリプト生成 (複数コマンドをまとめて実行)
    pub fn generate_batch_script(&self, resources: &[ResourceInfo], api_only: bool) -> String {
        let mut script = String::new();
        script.push_str("#!/bin/bash\n");
        script.push_str("# Generated Loco Scaffold Commands\n");
        script.push_str("# Generated by openapi-to-loco-scaf\n\n");
        
        script.push_str("set -e  # Exit on any error\n\n");
        
        for (i, resource) in resources.iter().enumerate() {
            script.push_str(&format!("echo \"[{}/{}] Generating scaffold for {}...\"\n", 
                i + 1, resources.len(), resource.name));
            script.push_str(&self.generate_single_command(resource, api_only));
            script.push_str(&format!("\necho \"✓ {} scaffold generated\"\n\n", &resource.name));
        }
        
        script.push_str("echo \"🎉 All scaffolds generated successfully!\"\n");
        script.push_str("echo \"Next steps:\"\n");
        script.push_str("echo \"1. Run 'cargo loco db migrate' to apply migrations\"\n");
        script.push_str("echo \"2. Run 'cargo loco db entities' to generate entities\"\n");
        script.push_str("echo \"3. Run 'cargo run start' to start your application\"\n");
        
        script
    }

    /// マークダウンレポート生成
    pub fn generate_report(&self, resources: &[ResourceInfo]) -> String {
        let mut report = String::new();
        
        report.push_str("# OpenAPI to Loco Scaffold Generation Report\n\n");
        report.push_str(&format!("Generated {} resources from OpenAPI specification.\n\n", resources.len()));
        
        report.push_str("## Resources Overview\n\n");
        for resource in resources {
            report.push_str(&format!("### {}\n\n", resource.name.to_case(Case::Title)));
            
            report.push_str("**Operations**: ");
            report.push_str(&resource.operations.join(", "));
            report.push_str("\n\n");
            
            if !resource.fields.is_empty() {
                report.push_str("**Fields**:\n\n");
                report.push_str("| Field | Type | Required | Unique | Reference |\n");
                report.push_str("|-------|------|----------|--------|----------|\n");
                
                for field in &resource.fields {
                    let type_name = match &field.field_type {
                        FieldType::References(table) => format!("references:{}", table),
                        _ => self.format_field_type(&field.field_type),
                    };
                    let required = if field.required { "✓" } else { "" };
                    let unique = if field.unique { "✓" } else { "" };
                    let reference = field.reference.as_deref().unwrap_or("");
                    
                    report.push_str(&format!("| {} | {} | {} | {} | {} |\n", 
                        field.name, type_name, required, unique, reference));
                }
                report.push_str("\n");
            }
            
            // 関係性情報を追加
            if !resource.relationships.is_empty() {
                report.push_str("**Relationships**:\n\n");
                for relationship in &resource.relationships {
                    let rel_type_str = match relationship.relationship_type {
                        RelationshipType::OneToOne => "1:1",
                        RelationshipType::OneToMany => "1:N",
                        RelationshipType::ManyToOne => "N:1", 
                        RelationshipType::ManyToMany => "N:N",
                    };
                    
                    report.push_str(&format!(
                        "- {} → {} ({})",
                        relationship.from_table,
                        relationship.to_table,
                        rel_type_str
                    ));
                    
                    if let Some(constraint) = &relationship.constraint {
                        report.push_str(&format!(" - {}", constraint));
                    }
                    report.push_str("\n");
                }
                report.push_str("\n");
            }
            
            report.push_str("**Generated Command**:\n");
            report.push_str("```bash\n");
            report.push_str(&self.generate_single_command(resource, true));
            report.push_str("\n```\n\n");
        }
        
        report.push_str("## Notes\n\n");
        report.push_str("- All commands use `--api` flag for API-only scaffolding\n");
        report.push_str("- Reference relationships are detected based on field naming conventions (`*_id`, `*Id`)\n");
        report.push_str("- Field types are mapped from OpenAPI types to Loco types\n");
        report.push_str("- Required fields are marked with `!` suffix\n\n");
        
        report.push_str("---\n");
        report.push_str("*Generated by [openapi-to-loco-scaf](https://github.com/your-repo/openapi-to-loco-scaf)*\n");
        
        report
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyzer::{FieldType, FieldInfo};

    fn create_test_resource() -> ResourceInfo {
        ResourceInfo {
            name: "posts".to_string(),
            fields: vec![
                FieldInfo {
                    name: "title".to_string(),
                    field_type: FieldType::String,
                    required: true,
                    unique: false,
                    reference: None,
                },
                FieldInfo {
                    name: "content".to_string(),
                    field_type: FieldType::Text,
                    required: false,
                    unique: false,
                    reference: None,
                },
                FieldInfo {
                    name: "user_id".to_string(),
                    field_type: FieldType::References("user".to_string()),
                    required: true,
                    unique: false,
                    reference: Some("user".to_string()),
                },
            ],
            operations: vec!["GET".to_string(), "POST".to_string()],
            relationships: Vec::new(),
        }
    }

    #[test]
    fn test_generate_single_command() {
        let generator = LocoScaffoldGenerator::new();
        let resource = create_test_resource();
        
        let command = generator.generate_single_command(&resource, true);
        let expected = "cargo loco generate scaffold posts title:string! content:text user_id:references:user! --api";
        
        assert_eq!(command, expected);
    }

    #[test]
    fn test_format_field_type() {
        let generator = LocoScaffoldGenerator::new();
        
        // String types
        assert_eq!(generator.format_field_type(&FieldType::String), "string");
        assert_eq!(generator.format_field_type(&FieldType::Text), "text");
        assert_eq!(generator.format_field_type(&FieldType::Uuid), "uuid");
        
        // Numeric types
        assert_eq!(generator.format_field_type(&FieldType::Integer), "int");
        assert_eq!(generator.format_field_type(&FieldType::BigInt), "big_int");
        assert_eq!(generator.format_field_type(&FieldType::Float), "float");
        assert_eq!(generator.format_field_type(&FieldType::Double), "double");
        assert_eq!(generator.format_field_type(&FieldType::Decimal), "decimal");
        
        // Other types
        assert_eq!(generator.format_field_type(&FieldType::Boolean), "bool");
        assert_eq!(generator.format_field_type(&FieldType::Date), "date");
        assert_eq!(generator.format_field_type(&FieldType::DateTime), "date_time");
        assert_eq!(generator.format_field_type(&FieldType::Json), "json");
        assert_eq!(generator.format_field_type(&FieldType::JsonBinary), "jsonb");
    }

    #[test]
    fn test_format_single_field() {
        let generator = LocoScaffoldGenerator::new();
        
        let string_field = FieldInfo {
            name: "title".to_string(),
            field_type: FieldType::String,
            required: true,
            unique: false,
            reference: None,
        };
        assert_eq!(generator.format_single_field(&string_field), "title:string!");
        
        let reference_field = FieldInfo {
            name: "user_id".to_string(),
            field_type: FieldType::References("user".to_string()),
            required: true,
            unique: false,
            reference: Some("user".to_string()),
        };
        assert_eq!(generator.format_single_field(&reference_field), "user_id:references:user!");
        
        // ユニーク制約のテスト
        let unique_field = FieldInfo {
            name: "email".to_string(),
            field_type: FieldType::String,
            required: true,
            unique: true, // ユニークが優先される
            reference: None,
        };
        assert_eq!(generator.format_single_field(&unique_field), "email:string^");
        
        let nullable_unique_field = FieldInfo {
            name: "username".to_string(),
            field_type: FieldType::String,
            required: false,
            unique: true,
            reference: None,
        };
        assert_eq!(generator.format_single_field(&nullable_unique_field), "username:string^");
    }
}